---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.3.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: mixed-line-ending
          - id: check-symlinks
          - id: check-added-large-files
    - repo: https://github.com/golangci/golangci-lint
      rev: v1.56.2
      hooks:
          - id: golangci-lint-full
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/mrtazz/checkmake.git
      rev: 0.2.2
      hooks:
          - id: checkmake
    - repo: https://github.com/Bahjat/pre-commit-golang
      rev: v1.0.2
      hooks:
          - id: go-fmt-import
          - id: go-vet
          - id: go-lint
          - id: go-unit-tests
          - id: gofumpt # requires github.com/mvdan/gofumpt
          - id: go-static-check # install https://staticcheck.io/docs/
